### ISSUE TITLE
naively calculated sigma and sigma in 0th block disagree

### ISSUE THREAD

**Issue by mcocdawc** [jsspencer/pyblock#18]
Hello,

Perhaps (probably) I am misunderstanding something about the blocking analysis in general,
but shouldn't the naive calculation of the standard deviation
and the standard deviation calculated from the first blocking step (with 2**0 == 1 blocks) be the same?

```python3
import pyblock
import numpy as np
import pandas as pd
from pandas import IndexSlice as idx

def corr_data(N, L):
    '''Generate random correlated data containing 2^N data points.
    Randon data is convolved over a 2^L/10 length to give the correlated signal.'''
    return np.convolve(np.random.randn(2**N), np.ones(2**L) / 10, 'same')

rand_data = pd.Series(corr_data(16, 6))

(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(rand_data)

# this passes
assert rand_data.size == data_length[0]
# this does not pass
assert np.isclose(rand_data.std(), reblock_data.loc[0, idx['data', 'standard error']])
```

PS: Note that the disagreement is two orders of magnitude and cannot be explained by slightly different denominators for the sample size in the estimator of the standard deviation.
(1 / (n_samples - 1) vs 1 / n_samples)

**Comment by mcocdawc** [comment]
I think I found the error. You have in your `blocking.reblock` function

```python3
if weights is None:
    nsamp = data_len
    mean = numpy.array(numpy.mean(data, axis=axis))
    cov = numpy.cov(data, rowvar=rowvar, ddof=ddof)
else:
   ....
if cov.ndim < 2:
    std_err = numpy.array(numpy.sqrt(cov/nsamp))
    # for (weights is None) correct would be 
    std_err = np.array(np.sqrt(cov))
else:
    ...
````

Of course it would be wrong to just change it to `std_err = np.array(np.sqrt(cov))`, because the upper `else` branch has:
```python3
            bessel = nsamp/(nsamp - ddof)
```
If this is changed to:
```python3
            bessel = 1 / (nsamp - ddof)
```
It should work. (Although then the name "bessel" is not fitting anymore.)

**Comment by mcocdawc** [comment]
Ok, I think I found my conceptional error.
You are not interested in the variance of the random variable, but in the variance of the estimator.
For this reason the variance expression has to be changed.

```
import pyblock
import numpy as np
import pandas as pd
from pandas import IndexSlice as idx

def corr_data(N, L):
    '''Generate random correlated data containing 2^N data points.
    Randon data is convolved over a 2^L/10 length to give the correlated signal.'''
    return np.convolve(np.random.randn(2**N), np.ones(2**L) / 10, 'same')

rand_data = pd.Series(corr_data(16, 6))

(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(rand_data)

# this passes
assert rand_data.size == data_length[0]
# this passes as well
assert np.isclose(np.sqrt(rand_data.std()**2 /  len(rand_data)), reblock_data.loc[0, idx['data', 'standard error']])
```

If you can confirm this, the issue can be closed.

**Comment by jsspencer** [comment]
First thanks for looking at this carefully and in detail. Communal attention improves all scientific codes and helps everyone. :-)

Your last comment is exactly correct. `pyblock` computes the standard error of the data (i.e. an estimate of the standard deviation in the population (sample) mean) rather than an standard deviation of the (exact) distribution.

The references cited in the documentation (especially Flyvbjerg and Petersen, which is a masterclass in how to communicate elegantly, clearly and compellingly in my view!) are particularly useful for understanding the motivation behind this analysis.

It may also be useful to consider what happens to the standard deviation and standard error during reblocking:

```
>>> data = corr_data(16, 6)
>>> stats = []
>>> while data.size > 2:
           stats.append((data.size, np.std(data), np.std(data)/np.sqrt(data.size)))
          data = (data[:-1:2] + data[1::2]) / 2
>>> pd.DataFrame(stats, columns=['# data', 'standard deviation', 'standard error']) 
    # data  standard deviation  standard error
0    65536            0.804595        0.003143
1    32768            0.801453        0.004427
2    16384            0.796738        0.006225
3     8192            0.787960        0.008706
4     4096            0.770544        0.012040
5     2048            0.734512        0.016231
6     1024            0.654269        0.020446
7      512            0.510819        0.022575
8      256            0.367538        0.022971
9      128            0.265048        0.023427
10      64            0.178250        0.022281
11      32            0.121586        0.021494
12      16            0.097919        0.024480
13       8            0.067313        0.023799
14       4            0.037263        0.018631
```

ps Assuming I'm right in thinking Solid State Research is in Stuttgart, say hi to Ali for me.

**Comment by mcocdawc** [comment]
Great! Thank you very much for your answer and the explanations.
I will follow your recommendation and read the Flyvbjerg and Petersen paper.

Regarding the PS: You are right in assuming that I am from Ali's group.
I will greet him from you. ;-)
