### ISSUE TITLE
Plotting reblock data where image size > 2^16 

### ISSUE THREAD

**Issue by wavymudkip** [jsspencer/pyblock#19]
I am using  the following to do block analysis on multiple columns of data(positions of atoms in my simulation):
```
(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(df)
```
The reblock data is something like this:
![image](https://user-images.githubusercontent.com/71371908/101982406-b9373d00-3c99-11eb-81bb-1c965e91b4c8.png)

However, when I try to plot this  `reblock_data` like following:
```
pyblock.plot.plot_reblocking(reblock_data);
```
But run into the following error: 
```
ValueError: Image size of 432x165888 pixels is too large. It must be less than 2^16 in each direction.

<Figure size 432x165888 with 576 Axes>
```

Mere slicing doesn't work on reblock data. What else can be tried?

**Comment by jsspencer** [comment]
Yes, in retrospect using hierarchical indices was a mistake and one I will fix when I get a moment. Using tidy data format will make slicing work much more naturally.

I think you're hitting a limitation of matplotlib. One option is to process the data in chunks -- either by only blocking a subset of atoms at a time or, given `reblock_data` by doing something like:

```
def chunk(df_wide, n=10):
    cols = df_wide.columns.get_level_values(0).unique()
    for i in range(0, len(cols), n):
        yield df_wide[cols[i:i+n]]

for df in chunk(reblock_data):
    pyblock.plot.plot_reblocking(df)
```

(where `n` just needs to be sufficiently small that you don't hit the figure limit).

574 plots is quite a lot though! Another alternative would be to create the plots yourself.
