### ISSUE TITLE
reblock if data.shape = (1, n)

### ISSUE THREAD

**Issue by Konjkov** [jsspencer/pyblock#20]
Hello reblock developers, I find reblock util is very usefull as part of my VMC package, but in the case when data.shape = (1, n) that equivalent to data.shape = (n, ) but is particular case of data.shape = (nvar, n) then pyblock.blocking.reblock(data) returns empty array.

I assume that the error can be found in the second part of the condition
https://github.com/jsspencer/pyblock/blob/master/pyblock/blocking.py#L79

Best Vladimir

**Comment by jsspencer** [comment]
Thanks for reporting this. Fixed. (You can also work around it by doing `np.squeeze(data)` before passing `data` into `blocking.reblock`.
