### ISSUE TITLE
mean

### ISSUE THREAD

**Issue by DJRankin** [jsspencer/pyblock#8]
Hi jsspencer

I have used your code to calculate the standard error of my correlated data using the pyblock.pd_utils.reblock() command. This works with no problem. I even tested it against a code that I made myself and they were in agreement with each other. However, I am confused as to why the mean reported for each blocking operation seems to depend on the number of blocking operations. This mean I got from the column called ('data', 'mean') in the pandas data frame that is output after using the command. The first value in the column is the correct mean of the data set and the others are all slightly different and depend on the number of blocking operations performed. It should not matter how many blocking operations one performs. The average of the re-blocked data is the same as the average of the original data set. Could you please explain why the 'mean' values vary with the number of blocking operations or if it is an error could you please fix it?

Thanks, Daniel.

**Comment by DJRankin** [comment]
Never mind, I have figured out that the average is different for different blocking operations due to some of the data being left out when the data is broken into blocks of different sizes.

**Comment by jsspencer** [comment]
Yes, exactly - this could be handled by weighting blocks differently but I haven't needed to do that (yet). No data is discarded only when the data size is a power of 2. I preferred to report the mean and error of the (sub)set of data used -- usually the estimates of the re-blocked data with serial correlations removed are within a standard error of the full correlated data set.
